### ISSUE TITLE
[Idea] Migrate to ReactiveDict

### ISSUE THREAD

**Issue by RobertLowe** [okgrow/meteor-persistent-session#11]
`Session` is entirely based on `ReactiveDict` now: https://github.com/meteor/meteor/blob/devel/packages/session/session.js

Since: https://github.com/meteor/meteor/commit/624035fab8fb27b1d4f5d884518d92dd3d52e5e0

So rather then adding all the functionality to `Session`, it could be added to `ReactiveDict`.

This has the advantage of being able to isolate a namespace/ReactiveDict.

Any thoughts?

Cheers!

**Comment by jhuenges** [comment]
Might be a nice idea. Havent done much with ReactiveDict, but i will take a look at it

**Comment by pauldowman** [comment]
@RobertLowe So do you mean you would you want to add it to all ReactiveDicts? Or do you mean that rather than having it available on Session you would have a separate persistent ReactiveDict available?

**Comment by RobertLowe** [comment]
@pauldowman no, not really but it depends on how it's implemented. I think injecting the functionality into `ReactiveDict` would be a poor choice over creating a new object. Something like:

`MyPackageSettings = PersistentReactiveDict('MyNameSpace')` where `PersistentReactiveDict` extends `ReactiveDict` would be useful.

Then the persistent session package would be one line: 

    Session = new PersistentReactiveDict('session');

using the let's say `persistent-reactive-dict` package. Like `Session` is with `ReactiveDict`: https://github.com/meteor/meteor/blob/devel/packages/session/session.js

OT: Another difficulty of `Session` +/- `persistent-session` is as an author you have to detect if it's used rather then just being able to trust your own namespace.

**Comment by pauldowman** [comment]
@RobertLowe I like this suggestion.

**Comment by rgould** [comment]
@RobertLowe Sorry for the super slow reply. This is a great idea, and we're definitely seeing how this is super useful, especially for writing packages. 

But we'd like to see a couple things first:

* Please fork the project from our repo, rather than creating a new one. This will help maintain code fixes between the repos, and will let us push fixes to you when we get them

* Please leave the code in Javascript. Personal opinions about Coffeescript aside, we want to keep the module in Javascript to minimise the barriers for contributions. Everyone who knows Coffeescript also knows Javascript, but not necessarily vice versa.

**Comment by RobertLowe** [comment]
Hey @rgould, no worries! (How have you been by the way?)

> Please fork the project from our repo, rather than creating a new one. This will help maintain code fixes between the repos, and will let us push fixes to you when we get them

I did this on purpose, it's kind of a different thing. I'm happy maintaining it as is. The reason I referenced it was to flag you guys about it's creation.

 > Please leave the code in Javascript. Personal opinions about Coffeescript aside, we want to keep the module in Javascript to minimise the barriers for contributions. Everyone who knows Coffeescript also knows Javascript, but not necessarily vice versa.

I disagree, which alone is probably a good reason for it being a fork. Yay, open source! I'm an opinionated developer and I enjoy working with CoffeeScript, I'm not optimizing for contribution barriers, I'm optimizing for developer happiness, productivity and for my own utility. Which is why `persistent-reactive-dict` is written in CS. 

Cheers!

**Comment by rgould** [comment]
@RobertLowe I'm well! Hope the same with you!

Yeah, I just figured if we used the same code base that it would make it easy to share bug fixes and patches quickly. But it's not a big deal at all, and it's a pretty small project anyway.
