### ISSUE TITLE
"undefined is not an object (evaluating 'e.route.getName')" 

### ISSUE THREAD

**Issue by advany** [okgrow/meteor-persistent-session#12]
When I use persistent-session I get the error above (only in production mode) and when I uninstall persistent session everything seems to be ok again...

**Comment by advany** [comment]
and removing setTemp everywhere fixed it... can't track how this happend, just reporting

**Comment by rgould** [comment]
Hi @advany! Is there any chance you can provide us with some more information? If you could include the full stack trace for the error, as well as the contents of your `.meteor/packages` file, that would help us immensely.

**Comment by advany** [comment]
I removed and reinstalled the package. Can't seem to replicate the error anymore...

**Comment by rgould** [comment]
Weird. Let us know if you come across it again!
