### ISSUE TITLE
Issue of Using u2622:persistent-session Package?

### ISSUE THREAD

**Issue by kasireddynv** [okgrow/meteor-persistent-session#13]
I using `u2622:persistent-session` in my project at that time i get one error.The error is "**Uncaught Error: Meteor does not currently support objects other than ObjectID as ids**".I didn't get any idea about this.So please suggest me what to for this issue?

**Comment by rgould** [comment]
Is there any chance you can provide us with some more information? If you could include the full stack trace for the error, as well as the contents of your `.meteor/packages` file, that would help us immensely.

From what I can see, it sounds like it is unrelated, and possibly caused during a `Collection.insert` call, where the `_id` field is trying to be set using an invalid value.

**Comment by kasireddynv** [comment]
Yes,But If i am not use this package it's works fine when ever i use to install this package and just runs `localhost:3000` then gets above error.Again removes this package works fine.So i am also get any idea about this.

**Comment by rgould** [comment]
@kasireddynv We need more info before we can debug this. Can you provide us with the information requested above, or perhaps the app itself? Then we'll take a look.

**Comment by kasireddynv** [comment]
@rgould 

Please find the  error : "Exception from Tracker recompute function: Meteor does not currently support objects other than ObjectID as ids
LocalCollection._idStringify@http://localhost:4000/packages/minimongo.js?e8806aa7782b729b2517ebc0cd10b321667f1427:1114:11
seqChangedToArray/seqArray<@http://localhost:4000/packages/observe-sequence.js?2fd807ea171ead273b9e6458607cb226012d9240:311:20
_.collect@http://localhost:4000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:174:1
seqChangedToArray@http://localhost:4000/packages/observe-sequence.js?2fd807ea171ead273b9e6458607cb226012d9240:295:18
ObserveSequence.observe/computation</<@http://localhost:4000/packages/observe-sequence.js?2fd807ea171ead273b9e6458607cb226012d9240:137:22
Tracker.nonreactive@http://localhost:4000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:513:12
ObserveSequence.observe/computation<@http://localhost:4000/packages/observe-sequence.js?2fd807ea171ead273b9e6458607cb226012d9240:121:7
Tracker.Computation.prototype._comput"[…]

**Comment by rgould** [comment]
@kasireddynv We've just released version 0.3.0, which may fix this issue. Can you try updating and see if you still have this problem?

**Comment by rgould** [comment]
@kasireddynv Going to close this issue. If you're still encountering it, please re-open it, preferably with demo meteor app that reproduces the problem.
