### ISSUE TITLE
Default-Method isn't temporary, but persistent

### ISSUE THREAD

**Issue by DanielDornhardt** [okgrow/meteor-persistent-session#14]
Hi, this just bit me - maybe I just misunderstood the docs, which say:

---

To define the default type for session variables, set persistent_session.default_method to your preferred type in your config/settings.json file:

    {
      "public": {
        "persistent_session": {
          "default_method": 'your-preferred-type'
        }
      }
    }

persistent_session.default_method can take one of the following values:

persistent
authenticated
In any other case the default_method will fall back to temporary

---

While in the code it is:

https://github.com/okgrow/meteor-persistent-session/blob/master/lib/persistent_session.js

    // initialize default method setting
    var default_method = 'persistent'; // valid options: 'temporary', 'persistent', 'authenticated'
    if (Meteor.settings &&
        Meteor.settings.public &&
        Meteor.settings.public.persistent_session) {
      default_method = Meteor.settings.public.persistent_session.default_method;
    }

- Did I misread the docs? I expected the default Session.set() and Session.get() - commands to stay temporary if Meteor.settings.public.persistent_session wan't set, but they were indeed persistent, which would confuse my code (and actually third party - code which relied on sessions being non-persistent).

**Comment by DanielDornhardt** [comment]
Also, it might be nice to document that the "persistent" - option also leads to session variables being shared across browser windows/tabs. That is implied by using localstorage, but that makes the behaviour differ from the default session in two major ways (persistent across reloads + shared between windows), not only one.

**Comment by nickw** [comment]
Agreed, it appears the docs are incorrect. I was just bit by this as well.

**Comment by pauldowman** [comment]
Thanks @DanielDornhardt and @nickw, and sorry for the slow reply. We'll fix it!

**Comment by pauldowman** [comment]
I tend to think it should be as the docs say, which will actually be a breaking change, what do you think @rgould? Definitely should bump the major version # then.

**Comment by nickw** [comment]
@pauldowman yeah, that was my expectation as well.

**Comment by rgould** [comment]
This should be fixed by df7386932a0ec9a162806111d4c0ec123ad32ab7, which has been released now. Reopen this if the issue persists!

**Comment by DanielDornhardt** [comment]
Thank you!
