### ISSUE TITLE
not clear with "Session.setAuth()" when user log out?

### ISSUE THREAD

**Issue by yuomtheara** [okgrow/meteor-persistent-session#20]
i use `Session.setAuth()` when user login, but when user logout the session don't auto clear.
Pl help me.

**Comment by rgould** [comment]
@yuomtheara Thanks for reporting this. We'll have a look and either fix a bug, or update the documentation

**Comment by rgould** [comment]
@yuomtheara I'm having trouble replicating this.

if I call `Session.setAuth('foo', "some data")`, it is cleared successfully when the user logs out. This is using `accounts-password` provided by meteor.

Which accounts packages are you using?

**Comment by yuomtheara** [comment]
yes, i use `accounts-password`.
but sometime cleared when the user log out.

**Comment by rgould** [comment]
@yuomtheara I'm still not able to replicate this issue. Are you still experiencing it? Can you try it with the latest version (0.3.2)?

**Comment by yuomtheara** [comment]
Now work fine.
Very thanks.
