### ISSUE TITLE
ReferenceError: EJSON is not defined

### ISSUE THREAD

**Issue by hansvn** [okgrow/meteor-persistent-session#22]
When I have a persistent session and I reload the page (in the browser) I get this error:
```javascript
ReferenceError: EJSON is not defined
http://localhost:3000/packages/u2622_persistent
session.js?03927d2509d2090e602b20a2b17c4c8399b28d8a
Line 100
psVal = EJSON.parse(Session.store('get', key));
```

I think this has to do with the package trying to load and parse the session vars before EJSON is loaded.

**Comment by jadsonlourenco** [comment]
Yes, get this error too...

**Comment by rgould** [comment]
Thanks! We'll hopefully get this one resolved quickly.

**Comment by gabriel-dehan** [comment]
+1

**Comment by pauldowman** [comment]
Yeah it needs to depend on the ejson package.

**Comment by jadsonlourenco** [comment]
I removed the package **msavin:mongol**, that use *babrahams:editable-json* and *gwendall:session-json* as dependency, so don't get this error any more. Like @pauldowman said is related with EJSON package, conflict?

**Comment by tcastelli** [comment]
+1! gettings EJSON.parse failed in many template helpers (expected string) reverted to 0.2.2 to fix it temporally

**Comment by zaklampert** [comment]
+1. any news here? also sticking with 0.2.2
