### ISSUE TITLE
Problem when using with package messageformat

### ISSUE THREAD

**Issue by tcastelli** [okgrow/meteor-persistent-session#24]
Hello, i was having this problem and some others and thought that everything would be fixed with the EJSON update, but still getting a lot of exceptions related to messageformat package (not happening with 0.2.2)
.....
"Exception in template helper: EJSON.parse@http://localhost:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:384:30
_psGet@http://localhost:3000/packages/u2622_persistent-session.js?0306d57630d05c163aba01e8e718801e18f08f4a:101:13
mf@http://localhost:3000/packages/gadicohen_messageformat.js?83c396c542f25fc81c0cdfc190e63eea66803f1a:1759:1
mfPkg.mfHelper@http://localhost:3000/packages/gadicohen_messageformat.js?83c396c542f25fc81c0cdfc190e63eea66803f1a:2558:9
bindDataContext/<@http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2786:14
Blaze._wrapCatchingExceptions/<@http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:1607:14
wrapHelper/</<@http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2834:14
Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:3382:12
wrapHelper/<@http://localhost:3000/packages/blaze.js?4e49999979a58da0e"[…]

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"Exception in delivering result of invoking 'mfLoadLangs': EJSON.parse@http://localhost:3000/packages/ejson.js?71047b64b5196348bdbe5fd5eea9ac97a5a9eb14:384:30
_psGet@http://localhost:3000/packages/u2622_persistent-session.js?0306d57630d05c163aba01e8e718801e18f08f4a:101:13
updateSubs@http://localhost:3000/packages/gadicohen_messageformat.js?83c396c542f25fc81c0cdfc190e63eea66803f1a:2715:15
mfPkg.loadLangs/<@http://localhost:3000/packages/gadicohen_messageformat.js?83c396c542f25fc81c0cdfc190e63eea66803f1a:2627:4
Meteor.bindEnvironment/<@http://localhost:3000/packages/meteor.js?e53378596562e8922a6369c955bab1e047fa866b:978:17
._maybeInvokeCallback@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3860:7
.receiveResult@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3880:5
._livedata_result@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:4970:7
Connection/onMessage@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3725:7
._launchConnection/self.socket.onmessage/<@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:2717:11
_.forEach@http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:156:7
._launchConnection/self.socket.onmessage@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:2716:9
SockJS</REventTarget.prototype.dispatchEvent@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:156:9
SockJS</SockJS.prototype._dispatchMessage@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:1141:5
SockJS</SockJS.prototype._didMessage@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:1199:13
SockJS</SockJS.websocket/that.ws.onmessage@http://localhost:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:1346:9
"

**Comment by rgould** [comment]
@tcastelli I can't seem to replicate this at all. It looks like a value is getting saved into Session that is not EJSONable. Perhaps there was a problem with the update from 0.2 to 0.3. If you clear your localStorage does the problem still persist?

**Comment by tcastelli** [comment]
Thanks for the hint, I tried to clear my localStorage and the page loaded again, so after looking for a while what was generating those non EJSONable parts i found out that at some point i use a package called planifica:wizard (for aldeed:autoform) that had created those values and were stored with amplify. (I guess i should contact the author to ask for an update, since that data is not compatible anymore with EJSON).

**Comment by rgould** [comment]
@tcastelli If they were stored in amplify (and not through `Session`) then you shouldn't be getting the error, as we shouldn't be trying to do `EJSON.parse` on all of the data in amplify. If that's the case this is definitely a bug on our side. Is that what is happening?

**Comment by tcastelli** [comment]
yes seems like the package is using amplify directly. I switched to
forwarder@wizard package to solve the issue,  since that one is using
session instead of amplify

**Comment by rgould** [comment]
Ah, yes. If something is set directly using `amplify.store` but then accessed using `Session.get`, that would cause this error. This can be fixed by having `Session.get` only attempt to use `EJSON.parse` if the key is a known key to persistent-session.

We'll fix this eventually, but I suspect this isn't commonly encountered, so it may be a few weeks. If anyone else encounters this, please :+1: here.

**Comment by deanius** [comment]
@rgould  - if things are merged, is the issue closable ?

**Comment by rgould** [comment]
@tcastelli This shouldn't be an issue anymore, but if you encounter it again, please re-open :)
