### ISSUE TITLE
Authenticated session variables are cleared when a new user clicks their email confirmation link

### ISSUE THREAD

**Issue by MichelFloyd** [okgrow/meteor-persistent-session#26]
1. User registers
 1. Create an authenticated Session variable with `Session.setAuth('foo',1)`
 1. User clicks on email confirmation link from Meteor accounts package
 1. `typeof Session.get('foo') == 'undefined'`

**Comment by rgould** [comment]
@MichelFloyd Thanks for the report! I wasn't able to reproduce it, but I can see how you may be running into this issue. 

At step 3, when the user clicks the confirmation link, if that opens in a different browser session, then that session will not see the previous browser's `localStorage`, and so will not be able to access the `foo` variable.

If you have some data that you want to persist across all browser sessions, it will need to be saved onto the current user via the `Meteor.users` collection.

However if it's the same browser session, there's a bug somewhere (which I wasn't able to duplicate).

Let me know if either of the above describe what you are experiencing

**Comment by MichelFloyd** [comment]
Thanks - by definition the confirmation link is going to open up a new tab/window since it’s sent via email and has to be clicked-on or pasted in to the URL bar.

**Comment by rgould** [comment]
@MichelFloyd `localStorage` is shared across the browser session, so it will work even in a new tab or window, as long as it's the same process, but that's often not the case with this kind of work flow.

Anyway, I'll close this. If you find another issue related to it, feel free to open. Thanks for reporting it in the first case!

**Comment by MichelFloyd** [comment]
Thank you Richard! This is a crypto app so I can’t save the data I need back to the server, I need to keep it in the client. I might have to resort to cookies!

What do you mean by “same process”? From the browser’s perspective it’s just another tab. Do you mean from Meteor’s perspective?

Everything I read about HTML5 local storage is that it should persist across tabs. Is Meteor account’s email verification killing local storage?
