### ISSUE TITLE
Session.get() always return null after update to 0.3.4 

### ISSUE THREAD

**Issue by ribbedcrown** [okgrow/meteor-persistent-session#28]
Hi! Thanks for great extension. I have a trouble after update to 0.3.4, `Session.get('key')` always returns *null* for both temporary and persistent keys used in app. All keys at local storage become equal *null*. After reverting version to 0.3.3 or removing package, it`s ok.
Meteor version 1.1.0.2, my config is set to persistent, but I've seen this behavior for all possible options.
``` json
{
  "public": {
    "persistent_session": {
      "default_method": "persistent"
    }
  }
}
```

**Comment by mj12albert** [comment]
This happens to me as well, even with session keys set directly in the devtools console in my hasty attempts to see if it was a problem with my code.

**Comment by lorensr** [comment]
For me unset session keys are returning the string `"null"`, which is bad because it evaluates to true, versus if it returned just `null`. When I remove the package, `Session.get('foo')` returns `false`.

**Comment by lorensr** [comment]
Sorry, it's not unset session keys, it's only one's that I've set to false:

```
Session.get('foo')
undefined
Session.set('foo',false)
undefined
Session.get('foo')
"null"
```

**Comment by solo999** [comment]
+1

**Comment by rgould** [comment]
Whoops, sorry about that. That was a sloppy release on my behalf. You should be able to keep it at 0.3.3 with no problems, and I'll have a fix out hopefully tomorrow.

**Comment by nicolamr** [comment]
Lol, just spent an hour debugging this.

**Comment by tcastelli** [comment]
+1 happening all the time with setTemp variables and got crazy debugging :_)

**Comment by rgould** [comment]
Sorry about that folks! That was sloppy on my behalf, and I'll be more careful about pushing updates in the future. More importantly, we'll push harder to get a solid test suite in place :)

I've reverted the offending commit and pushed version v0.3.5. I'll get around to fixing #27 soon (other work is getting in the way, unfortunately :( )
