### ISSUE TITLE
how to get the session on server?

### ISSUE THREAD

**Issue by yuomtheara** [okgrow/meteor-persistent-session#29]
Could I get the session on server?
Please help me.

**Comment by yuomtheara** [comment]
In my example, I have `Customer Collection` with branch office:
```js
{
name: 'A',
gender: 'M',
branchId: '001' 
},
{
name: 'B',
gender: 'M',
branchId: '002' 
}
```
1- When I login the system, I selected the select box for branch `001` so I set the session `currentBranch = 001`.
2- I open the list view of `customer` by current branch (I use `tabular` package to  show list view).
`Tabular` set on the server, so I can't get the session to find `customer` by current branch.
Have any solutions???

**Comment by rgould** [comment]
@yuomtheara - For server side data, you should store it on the user. Session isn't designed to work on the server.

For example, you could call `Meteor.users.update({_id: Meteor.userId}, { $set: { currentBranch: '001' } });` and then access that on the server with `Meteor.users.findOne(Meteor.userId).currentBranch`.
(Disclaimer: untested, so may not be exact)

Hope that helps!

**Comment by yuomtheara** [comment]
Very thanks for your explain, I think that it have problem when the same user login at the same time from different browser/PC (A user).
