### ISSUE TITLE
Session.setDefaultPersistent( { 'b': Random.id(), 'a': Random.id() } ) doesn't persist data

### ISSUE THREAD

**Issue by rslonik** [okgrow/meteor-persistent-session#32]
```
Session.setDefaultPersistent({ 
  'id': Random.id(), 
  'room_id': Random.id() 
});
```

The keys keep getting new values. Correct me if I'm wrong, but in the setDefault method, it should only assign a value if the key doesn't exists, right?

I'm not sure if the multiple keys should work with the setDefaultPersistent() like it does with setPersistent(), but I think so.

**Comment by rgould** [comment]
@rslonik Same as other issue: I wasn't ever able to replicate this, but it may be fixed in the new version (0.4.0). Can you confirm if this is still an issue?
