### ISSUE TITLE
Session.setPersistent does not update Session in other tabs without reloading

### ISSUE THREAD

**Issue by bhowell01** [okgrow/meteor-persistent-session#34]
I decided to use a homemade version of user authentication for my app (no Meteor.user). I would like to use this package to change my session variables "loggedIn" and "currentUser" to be persistent so that a user can be automatically logged in in multiple windows on the same client. I have implemented the package and within 5 minutes very easily got this to work (thanks!). The problem is that my layout html uses a helper that looks like this:

"login": function(){
    return !Session.get("loggedIn");
}

The idea is that when a user is not logged in, the login screen will appear instead of the {{> yield}} from iron router. When a user has 2 tabs open and logs out, the open tab will change to the login screen and then "loggedIn" and "currentUser" will be set to their proper values. The problem is that in the other tab, the session variables are changed but the template is not redrawn. This leaves the client in a loggedIn state with no data for currentUser. Is there a way to make templates redraw in all client instances when a persistent session variable is changed?

**Comment by jhuenges** [comment]
Maybe you could use Tracker.autorun?

**Comment by bhowell01** [comment]
This is my first Meteor project so I had not even heard of that but after looking at the documentation and playing around I can't seem to figure out how to make it redraw the template. If I put it in the helper it is only reachable when the template redraws right? I have been playing around with it and can't figure out how to force the template to redraw.

**Comment by jhuenges** [comment]
Can you paste some code? Maybe I can help you.

**Comment by bhowell01** [comment]
<template name="layout"> 
    {{#if login}}
        {{> loginScreen}}
    {{else}}
        {{> navBar}}
        <br><br>
        {{> yield}}
    {{/if}}
</template>

Template.layout.helpers({
  "login": function(){
    return !Session.get("loggedIn");
  }
});

"click #logOut": function(){ //in my navbar template
    Session.setPersistent("loggedIn", false);
    Session.setPersistent("currentUser",undefined);
  },

function login() { //function called from loginPage when user logs in
  var username = document.getElementById("username").value;
  var password = document.getElementById("password").value;
  Meteor.subscribe("findUserUP", username, password); //Subscribes to all fields for the current user's document
  setTimeout(function(){ //give the subscription a second to take effect
    Session.setPersistent("currentUser", Users.findOne({username: username, password: password}));
    if (Session.equals("currentUser",undefined)) {
      alert("Login failed. Please check your username and password.");
    } else {
      Session.setPersistent("loggedIn", true);
    }
  },60);
}

So normally as soon as loggedIn changes to true, the layout template is redrawn and the meat of the app appears. Because changing a session variable with setPersistent doesn't cause the templates in the other windows to redraw, they don't change to the login page.

**Comment by jhuenges** [comment]
This approach raises some concerns :/ Every user can change sessions to what ever he wants. So If I am not logged in and dont have an account. I could simply open my console and write
```javascript
Session.setPersisten("loggedIn", true)
```
Another flaw is 
```javascript
setTimeout(function(){ //give the subscription a second to take effect
  Session.setPersistent("currentUser", Users.findOne({username: username, password: password}));
  if (Session.equals("currentUser",undefined)) {
     alert("Login failed. Please check your username and password.");
  } else {
    Session.setPersistent("loggedIn", true);
  }
 },60);
```
You cant be sure that the subscription takes 60ms to get all the data.

Maybe you should think about another approach. Why does the Meteor accounts system not work for you?

**Comment by bhowell01** [comment]
Well this app is only going to be used internally in my company so I don't have to be quite as worried about security as I would with a normal application but my inexperienced self thought that taking out the insecure package (which I still have for development purposes) would deny users' access to session variables. Oops. Testing that scenario, no data is actually displayed on the website as everything checks for the qualification of "currentUser". Is there a way to store a variable that is accessible to all client code but can't be manipulated in the console? If I could store currentUser that way, that would be great.

I did not use the Meteor accounts system because I wanted to have complete control over all of the fields and functionality of the users. I had only been looking at Meteor for a few weeks when I made that decision; I just felt more comfortable doing it myself. Maybe that wasn't the best decision, but everything was functioning well with it, and I would prefer to not have to change all of my code

**Comment by jhuenges** [comment]
The only thing that comes to mind, are collections. They allow you to deny client updates and you can update the content from the server.

**Comment by bhowell01** [comment]
I'm going to have to change to the meteor accounts system. Thanks for helping me out

**Comment by pauldowman** [comment]
Is the original issue actually that it doesn't update the Session variable when it's changed on a different tab? I think that would be a good enhancement if so. There are events for localstorage, but we use Amplify which may actually be using other storage schemes, I'm not sure if Amplify has some portable events system but we could check it out.

**Comment by bhowell01** [comment]
When I was trying to use this idea, the session variables would change in the other tabs, but the templates did not redraw. So I would see that "loggedIn" was false in the other tab, but the template that relied on it's value only changed in the tab that was active when I changed the persistent session.

While my use case was flawed, it still seems like this would be an important feature since one of the main draws to using session variables is their reactive nature

**Comment by T-Grave** [comment]
:+1: 

I would love this, I've come across a couple of occasions when cross tab updates would be awesome.

**Comment by minfawang** [comment]
+1. Would love to see some progress on this.

**Comment by Greblak** [comment]
I used this code to accomplish it along with the simply:reactive-local-storage package, which makes localstorage reactive.

It's a bit of a hack though, but useful for the few times you need it. Perhaps something you can use to implement it properly ? :+1: 

```
Tracker.autorun(() => {
		if (RLocalStorage.getItem('__amplify__activeAlert') === null && Session.get('activeAlert') !== undefined)
			Session.set('activeAlert', undefined);

	});
```

**Comment by promentol** [comment]
if Persistent Session is using localStorage, using window.addEventListener('storage' other tab can catch the changed values, we may need for Persistent Session refresh like functionality then

**Comment by pauldowman** [comment]
Closing this old issue because this project is unsupported.
