### ISSUE TITLE
Session.setPersistent is not a function

### ISSUE THREAD

**Issue by ianmartorell** [okgrow/meteor-persistent-session#36]
I keep getting `Uncaught TypeError: Session.setPersistent is not a function`. As if I didn't have the package added, which obviously I do... What could it be?

**Comment by rgould** [comment]
@ianmartorell Looks like meteor changed how `Session` is loaded and it's breaking this package. Looking into a fix!

**Comment by rgould** [comment]
@ianmartorell Looks like I was mistaken, assuming you're still using 0.3.x. Perhaps it's a conflict with another package though. Do you mind posting your `.meteor/packages` and `.meteor/versions`?

**Comment by namirsab** [comment]
I have the same problem. Only setTemporary appears as a function

**Comment by namirsab** [comment]
Ok, i solved the next way. remove the package and install it specifying the last version. That's all.

**Comment by ianmartorell** [comment]
I couldn't find a way to get it to work when I opened this issue, so I found another way to do what I was trying to do without Session.  Now I'm using this package again and it's working great!
