### ISSUE TITLE
Values turned into strings

### ISSUE THREAD

**Issue by lorensr** [okgrow/meteor-persistent-session#37]
I haven't yet pinned down exactly in which cases this happens, but sometimes when I set to `false`, it later evaluates to true because the value has changed to the string `"false"`, I'm guessing after it's been written and read from `localStorage`.

**Comment by rgould** [comment]
@lorensr Thanks! I'll take a look.

**Comment by lorensr** [comment]
Has also happened with [] becoming "[]". A simple set, refresh, get doesn't
cause it tho.

**Comment by rgould** [comment]
@lorensr The changes introduced in 0.4.0 may have fixed this issue. Can you update and confirm if it's still occurring?

**Comment by lorensr** [comment]
Thanks! Upgraded, will let you know if I notice it again.

**Comment by lorensr** [comment]
I'm getting a lot of these errors, even in incognito: 

![image](https://cloud.githubusercontent.com/assets/251288/9020439/247f2a7a-37da-11e5-93e2-1d9107759072.png)

![image](https://cloud.githubusercontent.com/assets/251288/9020441/30693222-37da-11e5-9ec7-4cc4d4592caf.png)

**Comment by rico** [comment]
Having the same issue. For instance arrays are converted to strings. Using 0.4.0 with Meteor 1.1.0.2,. Thanks for looking into it.

**Comment by kaypro4** [comment]
I had the same issue as well using 0.4.0 and Meteor 1.1.0.3.  Rolling back to 0.3.5 resolved the issue for me.

**Comment by pauldowman** [comment]
@kaypro4 did you try 0.4.1?

**Comment by lorensr** [comment]
I'm no longer getting the `keyValueDeps` error in `0.4.1`

**Comment by kaypro4** [comment]
@pauldowman updating to 0.4.1 fixed the issue for me too.  Thanks!

**Comment by godblessmensah** [comment]
Am having this issue too, my nulls are being turn into "null".
Am using meteor 1.1.0.3 and 0.4.1.

**Comment by aramk** [comment]
Having the same issues. This is related to #45.

**Comment by smadsen** [comment]
+1
Empty arrays are saved as strings

![screen shot 2015-08-31 at 12 56 26](https://cloud.githubusercontent.com/assets/867391/9577303/cba628ae-4fdf-11e5-83df-c3805968d3c1.png)

**Comment by deanius** [comment]
If any of you can test if #47 fixes your issues and note it on the PR that'd be great!
