### ISSUE TITLE
What's the preferred way to expire a session?

### ISSUE THREAD

**Issue by nicolamr** [okgrow/meteor-persistent-session#38]
Does the session stay forever? If someone logs in in a public computer, the session should expire after a while. What's the best practice for this?

**Comment by pauldowman** [comment]
This doesn't change how long you're signed in to your Meteor app. To expire login after a period of time you can use the `loginExpirationInDays` option which is documented here: http://docs.meteor.com/#/full/accounts_config (but that doesn't actually solve the problem of people not logging out on a public computer, I think it's the user's responsibility to log out IMHO).

None of that is related to this package, but when using this package note that not everything is cleared when you sign out, check the [documentation](https://github.com/okgrow/meteor-persistent-session/blob/master/README.md) for `Session.setAuth()`
