### ISSUE TITLE
Session.clear(unusedKey) gives "Uncaught TypeError: Cannot read property 'undefined' of undefined"

### ISSUE THREAD

**Issue by rodcope1** [okgrow/meteor-persistent-session#42]
Until the latest release, it was okay to clear a key that hadn't been used yet.  Now it blows up.

I'd rather not have to check for the existence of a key before I try to clear it in initialization code.

**Comment by rgould** [comment]
@rodcope1 Thanks. We'll fix this!

**Comment by rgould** [comment]
This was fixed by #46 and has been released as of 0.4.2
