### ISSUE TITLE
How to disable console messages?

### ISSUE THREAD

**Issue by themeteorchef** [okgrow/meteor-persistent-session#48]
Whenever I load from persistent storage, I'm getting a handful of console messages:

![](http://cl.ly/image/262q1V191a3U/Image%202015-09-29%20at%2010.30.01%20AM.png)

Is there any way to turn this off?

**Comment by rgould** [comment]
@themeteorchef Thanks! Sorry about that. Leftover debugging messages that I accidentally committed. They've been removed in v0.4.3 which i've just released.

**Comment by themeteorchef** [comment]
No worries, thanks for the quick patch :)
