### ISSUE TITLE
After installing Meteor 1.2.0.2 Console shows the persistent Session name and values

### ISSUE THREAD

**Issue by nagarajay** [okgrow/meteor-persistent-session#49]
Hi There,

It seems after updating Meteor to 1.2.0.2 yesterday this package is giving the persistent Session names and values in the console. I have checked my code couple of times and felt I should share this with the community.

Please let me know if this is a cosmetic Bug or is it just me.

Thanks 
Ajay

**Comment by rgould** [comment]
@nagarajay Hi Ajay! This was an issue with 0.4.2 where some debug statements were accidentally committed. They've been removed in 0.4.3 :)

**Comment by nagarajay** [comment]
Thanks a lot. Cheers!!
