### ISSUE TITLE
Session in Flow Router

### ISSUE THREAD

**Issue by Christilut** [okgrow/meteor-persistent-session#52]
I tried to do a Session.clear() in an action method of a FlowRouter route but the clear didnt seem to do anything. This worked in Iron Router. 
If I take the clear() out of the route an put it in a helper method, it works just fine.

Is this intended?  

Edit: fixed it by using Meteor.defer() but should this be the normal way to do this in a flow route?

**Comment by rgould** [comment]
@Christilut Thanks Christiaan - this sounds like a bug. We'll check it out!

**Comment by rgould** [comment]
Sorry for taking so long. I tried to replicate this but it seems to be working as expected. If you're still encountering a problem please re-open this issue.
