### ISSUE TITLE
Document PersistentSession

### ISSUE THREAD

**Issue by HunterNL** [okgrow/meteor-persistent-session#53]
The documentation only shows saving the Session variable but the code exposes a PersistentSession which seems a lot nicer to use than throwing everything I want to persist into Session.

Could the readme be updated to reflect this? Right now it's seriously under"selling" the usefulness of this package.

Renaming PersistentSession to PersistentReactiveDict might go a bit far, but would make it clearer what this package does.

**Comment by pauldowman** [comment]
Actually I do think the package should be PersistentReactiveDict. :smile:

**Comment by pauldowman** [comment]
Closing this old issue because this project is unsupported.
