### ISSUE TITLE
how to set the expires value??

### ISSUE THREAD

**Issue by wubin1989** [okgrow/meteor-persistent-session#54]
how to set the expires value??

**Comment by jhuenges** [comment]
WHat do you mean with "expires"?

**Comment by wubin1989** [comment]
the localStorage property 'expires', I check it with develop tools of chrome, I saw {"data":true,"expires":null}

**Comment by rgould** [comment]
@wubin1989 The `expires` property is controlled by `amplifyjs`. What do you want to use it for? Setting a temporary session value that is cleared after a certain time?
