### ISSUE TITLE
Is this package supposed to support cross-tab updates?

### ISSUE THREAD

**Issue by Billybobbonnet** [okgrow/meteor-persistent-session#55]
If I use this package to set, e.g. authenticated variables, is this supposed to support cross browser tabs updates?

I gave it a try and it is not working but I wanted to check if I am not missing something before giving up.

Thanks

**Comment by rgould** [comment]
@Billybobbonnet this package uses `localstorage` on the backend, so it should persist across tabs, but it could be that the updates aren't being propagated. If that's the case, I'm not sure there's anything we can do it about it, but we'll take a look :)

**Comment by pauldowman** [comment]
@Billybobbonnet Do you mean that you need to refresh the second tab before the change is visible there? If so I think that's the same issue as #34, and see my comment [here](https://github.com/okgrow/meteor-persistent-session/issues/34#issuecomment-123463072)

**Comment by Billybobbonnet** [comment]
I wrapped your package variable in an autorun block like this:
``` javascript
Template.Example.rendered = function() {
  var self = this;
  self.autorun(function(){
      Session.get("myvar");
       //.....
  });
``` 

When I change this Session variable with, e.g. `Session.setAuth("myvar",newValue)` the autorun does not re-run in the other tab, and the Session variable is not updated.

**Comment by pauldowman** [comment]
@Billybobbonnet I think it's the same issue as #34. See my comment [here](https://github.com/okgrow/meteor-persistent-session/issues/34#issuecomment-123463072).
