### ISSUE TITLE
this support meteor 1.3 ?

### ISSUE THREAD

**Issue by lyquocnam** [okgrow/meteor-persistent-session#57]
this support meteor 1.3 ?
how can i import this ?

**Comment by rgould** [comment]
@lyquocnam I just tested and it seems to work with 1.3. There shouldn't be anything special that you need to do.

**Comment by thearabbit** [comment]
Excuse me, how to import this?
```js
import {Session} from  'meteor/session';
// or
import {Session} from  'meteor/u2622:persistent-session';
```
Which one?
