### ISSUE TITLE
Reactive persistent-session

### ISSUE THREAD

**Issue by TimeBandit** [okgrow/meteor-persistent-session#58]
Is this reactive? Perhaps the docs could be updated to show how this could be used reactively. If it is not possible then this would make a neat enhancement.

Currently it seems like if I wanted reactivity I would also store the data in a regular sessions var and keep it in synch with the persistent-session. The regular session would then be used where reactivity was important.

**Comment by rgould** [comment]
Yeah. The package makes some changes to `Session` itself, but it retains its reactivity. You would use this package just like you would use `Session`. The only big advantage is that it doesn't lose its values after a browser refresh.

If you're not seeing reactivity, then there is a bug. If that's the case, go ahead and re-open this :)
