### ISSUE TITLE
Explicit dependency on Meteor.Session

### ISSUE THREAD

**Issue by phoenixsupplies** [okgrow/meteor-persistent-session#63]
Thanks for making this useful package,
however you might want to update the docs for this package for Meteor 1.3 users.

I had assumed this was a drop in replacement for the Meteor package and tried using it on its own.  My blaze templates threw errors when I tried to get/set Session, but there was no error when I actually installed your package so it doesnt seem like Session is a dependency. 
Once I installed meteor/session the errors of course went away.

You could also make it clear that after installation the correct import command is still :
import { Session } from 'meteor/session';

**Comment by cfnelson** [comment]
The ReadMe has been updated with your suggestion. Thanks for pointing this out to us. 😄
