### ISSUE TITLE
Anyone using w/Meteor 1.7?

### ISSUE THREAD

**Issue by benlavalley** [okgrow/meteor-persistent-session#70]
I ran an upgrade to a Meteor 1.7 beta a month ago to try and resolve an issue I was having, and found this package was throwing errors.

I'm back on 1.6.1.1 for now, but wanted to ask if anyone using this package with Meteor 1.7 successfully?

**Comment by pauldowman** [comment]
Sorry @benlavalley but this project isn't supported any more, we no longer use it.

**Comment by benlavalley** [comment]
@pauldowman Understood and I saw the unsupported status, but I was curious to know if anyone else may have made any offline tweaks to the package and figured this was the best place to surface a possible issue.

**Comment by maxnowack** [comment]
I’m using this package right now and planning to build a 1.7 compatible alternative

**Comment by benlavalley** [comment]
@maxnowack - I should have looked for closed issues before posting - someone else had the same exact idea I did last week:

https://github.com/okgrow/meteor-persistent-session/issues/69

In the thread it's mentioned that another fork is 1.7-compatible:

https://github.com/cult-of-coders/meteor-persistent-session

There was another fork created where jQuery was removed as a dependency but it appears to be gone as of today (emailing author so he sees this thread).
